// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeE7K8I4Bex52El91Cl3mhu4KIpl2emyU',
    appId: '1:408136082031:web:c53350a8cbebdc2f02239a',
    messagingSenderId: '408136082031',
    projectId: 'hearthrythm-ac49e',
    authDomain: 'hearthrythm-ac49e.firebaseapp.com',
    storageBucket: 'hearthrythm-ac49e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAaFGCHGL8iaAw_Nre0h8wxllxeLQUGA',
    appId: '1:408136082031:android:09b8a48d1558e9fb02239a',
    messagingSenderId: '408136082031',
    projectId: 'hearthrythm-ac49e',
    storageBucket: 'hearthrythm-ac49e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1URQ6imTz1t0gM1QIk9hu8MkFDZA7Q4',
    appId: '1:408136082031:ios:def867630313563502239a',
    messagingSenderId: '408136082031',
    projectId: 'hearthrythm-ac49e',
    storageBucket: 'hearthrythm-ac49e.appspot.com',
    iosBundleId: 'com.example.hearthRythm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq1URQ6imTz1t0gM1QIk9hu8MkFDZA7Q4',
    appId: '1:408136082031:ios:def867630313563502239a',
    messagingSenderId: '408136082031',
    projectId: 'hearthrythm-ac49e',
    storageBucket: 'hearthrythm-ac49e.appspot.com',
    iosBundleId: 'com.example.hearthRythm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeE7K8I4Bex52El91Cl3mhu4KIpl2emyU',
    appId: '1:408136082031:web:127f5268ad0028bc02239a',
    messagingSenderId: '408136082031',
    projectId: 'hearthrythm-ac49e',
    authDomain: 'hearthrythm-ac49e.firebaseapp.com',
    storageBucket: 'hearthrythm-ac49e.appspot.com',
  );
}
